#!/usr/bin/env python3

import math
from typing import Final

PI: Final = math.pi
TWOPI: Final = 2.0 * math.pi

EARTH_POLAR_CIRCUMFERENCE_M: Final = 40_007_863
EARTH_EQUATORIAL_CIRCUMFERENCE_M: Final = 40_075_017

EARTH_POLAR_CIRCUMFERENCE_KM: Final = EARTH_POLAR_CIRCUMFERENCE_M / 1000.0
EARTH_EQUATORIAL_CIRCUMFERENCE_KM: Final = EARTH_EQUATORIAL_CIRCUMFERENCE_M / 1000.0
